### ISSUE TITLE
Why was Swift chosen for this wrapper module?

### ISSUE THREAD

**Issue by jeanregisser** [opentok/opentok-react-native#117]
Hi,

I noticed this wrapper is written in Swift.
The main problem with that is all people trying to integrate it into their React Native app will incur the cost of embedding the Swift runtime frameworks which is around 5MB.

From what I can tell the native OpenTok framework doesn't use Swift and works just fine in an ObjC only application.

I know Swift sounds cool and everything but for people writing React Native apps, it's quite uncool to have this additional 5MB just because they added OpenTok.

Is a rewrite to ObjC planned?

Added bonus, you would simplify the integration by not requiring Swift in other people's projects.

I see there's another alternative with https://github.com/callstack/react-native-opentok but I'd prefer to stick to the official integration (getting latest features and support).

**Comment by msach22** [comment]
@jeanregisser We wrote the library in Swift because we wanted to leverage the benefits of Swift and we've also seen more traction from our open source community with our Swift samples as opposed to Objective-C. 
 
As of now, we do not plan on rewriting the iOS bindings in Objective-C because we would like to focus on adding more features to the library.
