### ISSUE TITLE
[README] Add Camera & Microphone permissions info under iOS and Android installation 

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-react-native#37]

**Comment by ythecombinator** [comment]
Hey, I was puzzling here and I think that someone will have an issue similar to #36 on Android as well if they don't ask for permissions.

I am no Android developer but searching around I think about adding this to **iOS** section:

___

To enable camera usage and microphone usage you will need to add the following entries to your `Info.plist` file:

```
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microphone is accessed for the first time</string>
```

___

And this to **Android**'s one:

___

For most applications, you'll want to add camera and audio permissions to your `AndroidManifest.xml` file:

```xml
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    <uses-feature android:name="android.hardware.microphone" android:required="false" />
```

Newer versions of Android have a different permissions model.  You will need to use the `PermissionsAndroid`
class in `react-native` in order to request the `CAMERA` and `RECORD_AUDIO` permissions.

___

If you agree with this, I may open a PR adressing this issue.

**Comment by msach22** [comment]
@ythecombinator The iOS part looks great! As for Android, we are requesting the permissions using React Native here https://github.com/opentok/opentok-react-native/blob/master/src/OT.js#L7

**Comment by msach22** [comment]
As far as I know, the camera and microphone permissions for Android API Level 23 (Android 6.0) are classified as dangerous permissions so they need to be asked during runtime, which is what we are doing. 

As for the older Android devices, the items you suggested for `AndroidManifest.xml` work, except I believe that we need to set `android:required` to `true` for the following:
```
<uses-feature android:name="android.hardware.camera" android:required="true" />
<uses-feature android:name="android.hardware.microphone" android:required="true" />
```

Let me know what you think!

**Comment by ythecombinator** [comment]
Oh, great! I admit I hadn't read your source to check this 😆 

Btw, just opened the PR #38. Tried to follow the guidelines but if you find something to improve, I'll be happy to do so.

**Comment by ythecombinator** [comment]
Oh, just got your last comment. I'll update the Android section then.

**Comment by ythecombinator** [comment]
@msach22 as I mentioned, I'm not quite sure about the Android part since I found it googling around, tbh. If you think that's okay, I'll update the Android section then.

**Comment by ythecombinator** [comment]
Updated #38. Feel free to review :)

**Comment by msach22** [comment]
@ythecombinator the PR is great! The update will be going out with 0.4.2
