### ISSUE TITLE
iOS incorrect documentation?

### ISSUE THREAD

**Issue by dwilt** [opentok/opentok-react-native#381]
I would've filled out a bug report but it seemed like it would've made this more complicated than useful. 

In the [installation instructions for iOS](https://github.com/opentok/opentok-react-native#ios-installation), it seems like there are **2** sets of instructions titled: `For React Native < 0.60`.

![image](https://user-images.githubusercontent.com/1065539/74111037-3a87e580-4b46-11ea-9452-0b6d540694c1.png)

Is this correct or should the top section say `For React Native > 0.60` (greater than RN 60)?

**Comment by enricop89** [comment]
@dwilt For `React Native 0.60` you need to run a few more instructions, such as `react-native link opentok-react-native`

So, when you see the "**For React Native < 0.60**" section, it means you have to run those extra commands.

Note: RN >0.60 doesn't need manual linking, that's why you can skip the `react-native link opentok-react-native` command.

Thanks

**Comment by dwilt** [comment]
@enricop89 why have 2 headers with the same title then?
