### ISSUE TITLE
OTSubscriber no audio from background

### ISSUE THREAD

**Issue by adrian1388** [opentok/opentok-react-native#420]
# Bug Report

**Current behavior**
In my team, we are developing video calls for Android. When the app is foreground OTSubscriber works correctly, but when the callee accepts a call and the app comes from background, OTSubscriber is not reproducing audio.

**Steps to reproduce**
Basically, this is the code implemented:
``` (html)
<OTSession apiKey="your-api-key" sessionId="your-session-id" token="your-session-token" options={{ androidOnTop: "publisher" }}>
    <OTSubscriber style={{ width: "100%", height: "100%" }} />
    <OTPublisher style={{ width: 50, height: 50 }}/>
</OTSession>
```

**What is the current *bug* behavior?**
OTSubscriber gives only video but not audio

**What is the expected *correct* behavior?**
OTSubscriber must give video and audio

**Comment by hazemzuhair** [comment]
Please Help Me , same problem !

**Comment by ganesh-papola** [comment]
same problem with me, There is no audio on video call. also sometime the subscriber video is empty / black screen only.
no solution yet...

**Comment by enricop89** [comment]
Hello, thanks for filling the issue. Could you explain me better the steps to reproduce it please?

`but when the callee accepts a call and the app comes from background, OTSubscriber is not reproducing audio.`

This is not clear to me. What do you mean by accepts a call?

**Comment by adrian1388** [comment]
My bad...
Please imagine a Video Call implementation (I am using [React Native Callkeep](https://github.com/react-native-webrtc/react-native-callkeep)) in which both users share each other the 'apiKey', 'sessionId' and the 'token' properties.

When one of these users receives and tap a push notification, which opens the application, it is supposed to open the OTSession window. But there is when I have the bug.

I have tested with some delays opening our window after the tap of the notification, but nothing works.

**Comment by evillemez** [comment]
So I can't add anything very specific - because the behavior is inconsistent for us.  But, we have had increasing reports from users of our app that they will end up in a call where one side cannot hear audio from the other side, but both are receiving video fine.

In some cases I have also verified via the Tokbox Inspector that both sides were subscribed to each other and receiving both audio and video.

I have some semi-supported theories, and some wild ass gueses for our case:

* some evidence is suggesting to me that this may specifically be a problem with iOS 14.2 - but I'm not fully convinced
* We also recently added support for React Native CallKeep, mentioned by @adrian1388 - but we had reports of this issue before that build was released to the public
* We know of issues in previous builds of our, also related to iOS 14.2 - where pushing on the visible push notification we send in order to open our app and accept the incoming call, would cause a crash, or other unexpected behavior.  Based on the comment from @adrian1388 I'm starting to wonder if the possibility of tapping the notification to open the app might be a trigger.

I know this isn't super helpful, but I'm also grasping at straws.

**Comment by enricop89** [comment]
@evillemez thanks for your comment. We are aware of audio issues on iOS 14.2 ([webkit-issue-1](https://bugs.webkit.org/show_bug.cgi?id=218762) and [webkit-issue-2](https://bugs.webkit.org/show_bug.cgi?id=218762).
but they are all related to Safari, not to the native SDK. 

Are your users able to connect only using the app or also using Safari?
