### ISSUE TITLE
Subscriber reconnect event

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#59]
Is there a way to track when Subscriber reconnect after a disconnection?

**Comment by renanpupin** [comment]
Subscriber has 2 listeners: connected and disconnected.
The connected listener is executed when starts, but after a disconnection it does not execute anymore.

**Comment by msach22** [comment]
@renanpupin Unfortuantely, you cannot use the event listeners to see if it's the same subscriber after disconnection and reconnection events because when a user is disconnected and then reconnects, they are given a new connection ID. However, you can generate a UUID and add that as a part of the token data and map that to connectionIds when the user connects to the session. This way when a `connectionCreated` event is dispatched,  you can see that token data(UUID in this case) as property of the connection object.

**Comment by msach22** [comment]
I'm closing this issue because it's not an issue with the library. Let me know if you have any questions!

**Comment by renanpupin** [comment]
@msach22 I have listeners for all events of session, subscriber and publisher. However when I disconnect from one side and reconnect after, the only event that executes is "disconnected" from Subscriber and the "connectionCreated" event does not execute.
So I still think it is a bug with the library.
Thanks.

**Comment by renanpupin** [comment]
@msach22 on javascript web sdk, the events is executing normally.
