### ISSUE TITLE
Support for Vonage IP Proxy

### ISSUE THREAD

**Issue by ashkan-pm** [opentok/opentok-react-native#645]
Hello! First of all, thanks a lot for this package. I had a question regarding setting up the IP Proxy documented here: https://tokbox.com/developer/guides/ip-proxy/

I can see that there is some code in the `OTSession` component that accepts a `proxyUrl` as part of the `options` prop. But it seems like the types in the package don't reflect that and I get a TS error when trying to set this option. I tried ignoring TS and setting the option anyway. And it seems like it works to some extent. I can see the `ClientEvent` POST requests going through the proxy, but the video call itself will not work with the `proxyUrl` set. It throws this error:

`Video-call error {"code": 1022, "message": "The connection to the OpenTok messaging server was dropped. Check the network connection."}`

So I would like to know, is this proxy feature supported by this package? Is it documented anywhere? And if so I'd appreciate if you can help in getting the video call to work with the proxy set. Thanks in advance.

**Comment by pietgk** [comment]
This is also very relevant for us, so can we get feedback now that RN is officially supported?

**Comment by jeffswartz** [comment]
We have verified that the `ipProxy` setting was fixed in Android but not in iOS in version 0.21.3+ of the OpenTok React Native SDK.

There was an underlying bug that was fixed in  v2.24.0 of the OpenTok iOS and Android SDKs. In v0.21.3 of the OpenTok React Native SDK, we were able to update to v.2.24.2 of the OpenTok Android SDK. However, there is an issue in the OpenTok iOS SDK v2.24.x+ that prevents us from using it in our React Native SDK. We are working on fixing the issue in the OpenTok iOS SDK.
